#!/bin/bash

_tabalot () {
    COMPREPLY=($(
		"$1" --tabalot $(( $COMP_CWORD - 1 )) "${COMP_WORDS[@]:1}" 2> /dev/null
    ))
}

if [ -f ~/.tabalot/completions ]; then
	TABALOT=""
	while read app; do
		TABALOT="$TABALOT:$app"
		complete -F _tabalot "$app"
	done < ~/.tabalot/completions
	export TABALOT="${TABALOT:1}"
fi
